before_script:
  - export GOPATH=/var/go
  - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
  - ORG_DIR="$GOPATH/src/github.com/ultramesh"
  - mkdir -p $ORG_DIR
  - PROJECT_DIR="$ORG_DIR/$CI_PROJECT_NAME"
  - echo $ORG_DIR
  - echo $PROJECT_DIR
  - mkdir -p $ORG_DIR
  - rm -rf $PROJECT_DIR
  - ln -sfv "$(pwd -P)" "$PROJECT_DIR"
  - cd "$PROJECT_DIR"
  - export GO111MODULE=on

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - rm -rf /usr/local/go
    - ln -s /usr/local/go1.10.2 /usr/local/go
    - echo lint go version
    - go version
    - cd "$PROJECT_DIR" && ./scripts/fmt.sh
  allow_failure: true

test:
  stage: test
  script:
    - rm -rf /usr/local/go
    - ln -s /usr/local/go1.12.4 /usr/local/go
    - echo test go version
    - go version
    - pwd
    - go env
    - ./scripts/gomod.sh
    - cd "$PROJECT_DIR" && CGO_LDFLAGS_ALLOW=.* CGO_CFLAGS_ALLOW=.* go test ./...
    - rm -rf /tmp/solctest.info.json
