// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: checkpoint.proto

package consensus

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Checkpoint struct {
	Epoch           uint64                   `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ExecuteState    *Checkpoint_ExecuteState `protobuf:"bytes,2,opt,name=execute_state,json=executeState,proto3" json:"execute_state,omitempty"`
	NeedUpdateEpoch bool                     `protobuf:"varint,3,opt,name=need_update_epoch,json=needUpdateEpoch,proto3" json:"need_update_epoch,omitempty"`
	NewView         uint64                   `protobuf:"varint,4,opt,name=new_view,json=newView,proto3" json:"new_view,omitempty"`
}

func (m *Checkpoint) Reset()      { *m = Checkpoint{} }
func (*Checkpoint) ProtoMessage() {}
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bab050ffa824783, []int{0}
}
func (m *Checkpoint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Checkpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Checkpoint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Checkpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint.Merge(m, src)
}
func (m *Checkpoint) XXX_Size() int {
	return m.Size()
}
func (m *Checkpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint proto.InternalMessageInfo

func (m *Checkpoint) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Checkpoint) GetExecuteState() *Checkpoint_ExecuteState {
	if m != nil {
		return m.ExecuteState
	}
	return nil
}

func (m *Checkpoint) GetNeedUpdateEpoch() bool {
	if m != nil {
		return m.NeedUpdateEpoch
	}
	return false
}

func (m *Checkpoint) GetNewView() uint64 {
	if m != nil {
		return m.NewView
	}
	return 0
}

// Execute state of the executed block
type Checkpoint_ExecuteState struct {
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Digest string `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
}

func (m *Checkpoint_ExecuteState) Reset()         { *m = Checkpoint_ExecuteState{} }
func (m *Checkpoint_ExecuteState) String() string { return proto.CompactTextString(m) }
func (*Checkpoint_ExecuteState) ProtoMessage()    {}
func (*Checkpoint_ExecuteState) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bab050ffa824783, []int{0, 0}
}
func (m *Checkpoint_ExecuteState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Checkpoint_ExecuteState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Checkpoint_ExecuteState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Checkpoint_ExecuteState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint_ExecuteState.Merge(m, src)
}
func (m *Checkpoint_ExecuteState) XXX_Size() int {
	return m.Size()
}
func (m *Checkpoint_ExecuteState) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint_ExecuteState.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint_ExecuteState proto.InternalMessageInfo

func (m *Checkpoint_ExecuteState) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Checkpoint_ExecuteState) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

// SignedCheckpoint contains the actual checkpoint with signature
type SignedCheckpoint struct {
	// Checkpoint is the info of checkpoint.
	Checkpoint *Checkpoint `protobuf:"bytes,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	// Author is the signer for signature.
	Author uint64 `protobuf:"varint,2,opt,name=author,proto3" json:"author,omitempty"`
	// Signature is the signature for checkpoint.
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *SignedCheckpoint) Reset()      { *m = SignedCheckpoint{} }
func (*SignedCheckpoint) ProtoMessage() {}
func (*SignedCheckpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bab050ffa824783, []int{1}
}
func (m *SignedCheckpoint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SignedCheckpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SignedCheckpoint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SignedCheckpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedCheckpoint.Merge(m, src)
}
func (m *SignedCheckpoint) XXX_Size() int {
	return m.Size()
}
func (m *SignedCheckpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedCheckpoint.DiscardUnknown(m)
}

var xxx_messageInfo_SignedCheckpoint proto.InternalMessageInfo

func (m *SignedCheckpoint) GetCheckpoint() *Checkpoint {
	if m != nil {
		return m.Checkpoint
	}
	return nil
}

func (m *SignedCheckpoint) GetAuthor() uint64 {
	if m != nil {
		return m.Author
	}
	return 0
}

func (m *SignedCheckpoint) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// QuorumCheckpoint contains the actual checkpoint with signatures
// by different quorum validators
type QuorumCheckpoint struct {
	// Checkpoint is the info of checkpoint.
	Checkpoint *Checkpoint `protobuf:"bytes,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	// Signatures is the aggregated signature for checkpoint.
	Signatures map[uint64][]byte `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *QuorumCheckpoint) Reset()      { *m = QuorumCheckpoint{} }
func (*QuorumCheckpoint) ProtoMessage() {}
func (*QuorumCheckpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bab050ffa824783, []int{2}
}
func (m *QuorumCheckpoint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuorumCheckpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuorumCheckpoint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuorumCheckpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuorumCheckpoint.Merge(m, src)
}
func (m *QuorumCheckpoint) XXX_Size() int {
	return m.Size()
}
func (m *QuorumCheckpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_QuorumCheckpoint.DiscardUnknown(m)
}

var xxx_messageInfo_QuorumCheckpoint proto.InternalMessageInfo

func (m *QuorumCheckpoint) GetCheckpoint() *Checkpoint {
	if m != nil {
		return m.Checkpoint
	}
	return nil
}

func (m *QuorumCheckpoint) GetSignatures() map[uint64][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

// EpochChangeProof is a slice of checkpoints with contiguous increasing epoch numbers
// to prove a sequence if epoch changes from the first checkpoint's epoch
type EpochChangeProof struct {
	EpochChanges []*EpochChange `protobuf:"bytes,1,rep,name=epoch_changes,json=epochChanges,proto3" json:"epoch_changes,omitempty"`
	// Indicate whether the node where proof comes from has more epoch changes
	More uint64 `protobuf:"varint,2,opt,name=more,proto3" json:"more,omitempty"`
	// Where the proof comes from
	Author uint64 `protobuf:"varint,3,opt,name=author,proto3" json:"author,omitempty"`
	// Help remote check genesis block digest
	GenesisBlockDigest string `protobuf:"bytes,4,opt,name=genesis_block_digest,json=genesisBlockDigest,proto3" json:"genesis_block_digest,omitempty"`
}

func (m *EpochChangeProof) Reset()      { *m = EpochChangeProof{} }
func (*EpochChangeProof) ProtoMessage() {}
func (*EpochChangeProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bab050ffa824783, []int{3}
}
func (m *EpochChangeProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochChangeProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochChangeProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochChangeProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochChangeProof.Merge(m, src)
}
func (m *EpochChangeProof) XXX_Size() int {
	return m.Size()
}
func (m *EpochChangeProof) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochChangeProof.DiscardUnknown(m)
}

var xxx_messageInfo_EpochChangeProof proto.InternalMessageInfo

func (m *EpochChangeProof) GetEpochChanges() []*EpochChange {
	if m != nil {
		return m.EpochChanges
	}
	return nil
}

func (m *EpochChangeProof) GetMore() uint64 {
	if m != nil {
		return m.More
	}
	return 0
}

func (m *EpochChangeProof) GetAuthor() uint64 {
	if m != nil {
		return m.Author
	}
	return 0
}

func (m *EpochChangeProof) GetGenesisBlockDigest() string {
	if m != nil {
		return m.GenesisBlockDigest
	}
	return ""
}

type EpochChange struct {
	// The slice of quorum checkpoints
	Checkpoint *QuorumCheckpoint `protobuf:"bytes,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	// Help remote node sync from validators
	Validators []string `protobuf:"bytes,2,rep,name=validators,proto3" json:"validators,omitempty"`
}

func (m *EpochChange) Reset()         { *m = EpochChange{} }
func (m *EpochChange) String() string { return proto.CompactTextString(m) }
func (*EpochChange) ProtoMessage()    {}
func (*EpochChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bab050ffa824783, []int{4}
}
func (m *EpochChange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochChange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochChange.Merge(m, src)
}
func (m *EpochChange) XXX_Size() int {
	return m.Size()
}
func (m *EpochChange) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochChange.DiscardUnknown(m)
}

var xxx_messageInfo_EpochChange proto.InternalMessageInfo

func (m *EpochChange) GetCheckpoint() *QuorumCheckpoint {
	if m != nil {
		return m.Checkpoint
	}
	return nil
}

func (m *EpochChange) GetValidators() []string {
	if m != nil {
		return m.Validators
	}
	return nil
}

func init() {
	proto.RegisterType((*Checkpoint)(nil), "consensus.Checkpoint")
	proto.RegisterType((*Checkpoint_ExecuteState)(nil), "consensus.Checkpoint.ExecuteState")
	proto.RegisterType((*SignedCheckpoint)(nil), "consensus.SignedCheckpoint")
	proto.RegisterType((*QuorumCheckpoint)(nil), "consensus.QuorumCheckpoint")
	proto.RegisterMapType((map[uint64][]byte)(nil), "consensus.QuorumCheckpoint.SignaturesEntry")
	proto.RegisterType((*EpochChangeProof)(nil), "consensus.EpochChangeProof")
	proto.RegisterType((*EpochChange)(nil), "consensus.EpochChange")
}

func init() { proto.RegisterFile("checkpoint.proto", fileDescriptor_9bab050ffa824783) }

var fileDescriptor_9bab050ffa824783 = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xcd, 0x24, 0xfe, 0xfa, 0x35, 0x37, 0xa9, 0x1a, 0x46, 0xa5, 0x32, 0x01, 0x99, 0x28, 0xab,
	0x08, 0x84, 0x8b, 0x82, 0x90, 0x50, 0x2b, 0x58, 0xb4, 0x44, 0x2c, 0xd8, 0xc0, 0x44, 0xb0, 0xb5,
	0x1c, 0xe7, 0xd6, 0x36, 0x49, 0x66, 0x22, 0xcf, 0x38, 0xa1, 0x0f, 0xc0, 0x9e, 0x25, 0x4b, 0xde,
	0x81, 0x97, 0x60, 0xd9, 0x25, 0x12, 0x1b, 0x94, 0xbc, 0x04, 0x4b, 0xe4, 0xf1, 0x28, 0x99, 0x56,
	0x15, 0x1b, 0x76, 0x3e, 0xf7, 0xef, 0x9c, 0x39, 0xf7, 0x1a, 0x5a, 0x51, 0x82, 0xd1, 0x64, 0x2e,
	0x52, 0xae, 0xfc, 0x79, 0x26, 0x94, 0xa0, 0xf5, 0x48, 0x70, 0x89, 0x5c, 0xe6, 0xb2, 0xfd, 0x28,
	0x4e, 0x55, 0x92, 0x8f, 0xfc, 0x48, 0xcc, 0x8e, 0x62, 0x11, 0x8b, 0x23, 0x5d, 0x31, 0xca, 0xcf,
	0x35, 0xd2, 0x40, 0x7f, 0x95, 0x9d, 0xdd, 0xdf, 0x04, 0xe0, 0x6c, 0x33, 0x8e, 0x1e, 0xc0, 0x7f,
	0x38, 0x17, 0x51, 0xe2, 0x92, 0x0e, 0xe9, 0x39, 0xac, 0x04, 0xf4, 0x15, 0xec, 0xe1, 0x47, 0x8c,
	0x72, 0x85, 0x81, 0x54, 0xa1, 0x42, 0xb7, 0xda, 0x21, 0xbd, 0x46, 0xbf, 0xeb, 0x6f, 0x68, 0xfd,
	0xed, 0x0c, 0x7f, 0x50, 0x96, 0x0e, 0x8b, 0x4a, 0xd6, 0x44, 0x0b, 0xd1, 0x07, 0x70, 0x8b, 0x23,
	0x8e, 0x83, 0x7c, 0x3e, 0x0e, 0x15, 0x06, 0x25, 0x55, 0xad, 0x43, 0x7a, 0xbb, 0x6c, 0xbf, 0x48,
	0xbc, 0xd3, 0xf1, 0x81, 0x26, 0xbd, 0x03, 0xbb, 0x1c, 0x97, 0xc1, 0x22, 0xc5, 0xa5, 0xeb, 0x68,
	0x35, 0xff, 0x73, 0x5c, 0xbe, 0x4f, 0x71, 0xd9, 0x7e, 0x01, 0x4d, 0x9b, 0x84, 0x1e, 0xc2, 0x4e,
	0x82, 0x69, 0x9c, 0x28, 0x23, 0xdb, 0xa0, 0x22, 0x3e, 0x4e, 0x63, 0x94, 0x4a, 0x0b, 0xae, 0x33,
	0x83, 0x8e, 0x9d, 0x2f, 0x5f, 0xef, 0x57, 0xba, 0x9f, 0x08, 0xb4, 0x86, 0x69, 0xcc, 0x71, 0x6c,
	0x19, 0xf0, 0x14, 0x60, 0xeb, 0xae, 0x1e, 0xd7, 0xe8, 0xdf, 0xbe, 0xf1, 0x9d, 0xcc, 0x2a, 0x2c,
	0x98, 0xc2, 0x5c, 0x25, 0x22, 0xd3, 0x4c, 0x0e, 0x33, 0x88, 0xde, 0x83, 0xba, 0x4c, 0x63, 0x1e,
	0xaa, 0x3c, 0x43, 0xfd, 0xd0, 0x26, 0xdb, 0x06, 0x8c, 0x8e, 0x9f, 0x04, 0x5a, 0x6f, 0x73, 0x91,
	0xe5, 0xb3, 0x7f, 0xd7, 0xf1, 0x1a, 0x60, 0x33, 0x5e, 0xba, 0xd5, 0x4e, 0xad, 0xd7, 0xe8, 0x3f,
	0xb4, 0xda, 0xae, 0xf3, 0xf8, 0xc3, 0x4d, 0xf5, 0x80, 0xab, 0xec, 0x82, 0x59, 0xed, 0xed, 0xe7,
	0xb0, 0x7f, 0x2d, 0x4d, 0x5b, 0x50, 0x9b, 0xe0, 0x85, 0xb1, 0xb9, 0xf8, 0x2c, 0x2e, 0x66, 0x11,
	0x4e, 0xf3, 0xf2, 0x26, 0x9a, 0xac, 0x04, 0xc7, 0xd5, 0x67, 0xc4, 0xbc, 0xee, 0x1b, 0x81, 0x96,
	0x5e, 0xe8, 0x59, 0x12, 0xf2, 0x18, 0xdf, 0x64, 0x42, 0x9c, 0xd3, 0x13, 0xd8, 0xd3, 0xbb, 0x0f,
	0x22, 0x1d, 0x94, 0x2e, 0xd1, 0x4a, 0x0f, 0x2d, 0xa5, 0x56, 0x0f, 0x6b, 0xe2, 0x16, 0x48, 0x4a,
	0xc1, 0x99, 0x89, 0x0c, 0x8d, 0xd3, 0xfa, 0xdb, 0xf2, 0xbf, 0x76, 0xc5, 0xff, 0xc7, 0x70, 0x10,
	0x23, 0x47, 0x99, 0xca, 0x60, 0x34, 0x15, 0xd1, 0x24, 0x30, 0xf7, 0xe0, 0xe8, 0x7b, 0xa0, 0x26,
	0x77, 0x5a, 0xa4, 0x5e, 0xda, 0xb7, 0xf1, 0x01, 0x1a, 0x96, 0x00, 0x7a, 0x72, 0xc3, 0x36, 0xee,
	0xfe, 0xc5, 0xd6, 0x2b, 0x3b, 0xf1, 0x00, 0x16, 0xe1, 0x34, 0x1d, 0x87, 0x4a, 0x64, 0xe5, 0x4e,
	0xea, 0xcc, 0x8a, 0x9c, 0xba, 0xdf, 0x57, 0x1e, 0xb9, 0x5c, 0x79, 0xe4, 0xd7, 0xca, 0x23, 0x9f,
	0xd7, 0x5e, 0xe5, 0x72, 0xed, 0x55, 0x7e, 0xac, 0xbd, 0xca, 0x68, 0x47, 0xff, 0xa3, 0x4f, 0xfe,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xea, 0x5d, 0x9e, 0xf1, 0x03, 0x00, 0x00,
}

func (m *Checkpoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Checkpoint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Checkpoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NewView != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.NewView))
		i--
		dAtA[i] = 0x20
	}
	if m.NeedUpdateEpoch {
		i--
		if m.NeedUpdateEpoch {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.ExecuteState != nil {
		{
			size, err := m.ExecuteState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCheckpoint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Epoch != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Checkpoint_ExecuteState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Checkpoint_ExecuteState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Checkpoint_ExecuteState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Digest) > 0 {
		i -= len(m.Digest)
		copy(dAtA[i:], m.Digest)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.Digest)))
		i--
		dAtA[i] = 0x12
	}
	if m.Height != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SignedCheckpoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SignedCheckpoint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SignedCheckpoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Author != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.Author))
		i--
		dAtA[i] = 0x10
	}
	if m.Checkpoint != nil {
		{
			size, err := m.Checkpoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCheckpoint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuorumCheckpoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuorumCheckpoint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuorumCheckpoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signatures) > 0 {
		for k := range m.Signatures {
			v := m.Signatures[k]
			baseI := i
			if len(v) > 0 {
				i -= len(v)
				copy(dAtA[i:], v)
				i = encodeVarintCheckpoint(dAtA, i, uint64(len(v)))
				i--
				dAtA[i] = 0x12
			}
			i = encodeVarintCheckpoint(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintCheckpoint(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Checkpoint != nil {
		{
			size, err := m.Checkpoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCheckpoint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EpochChangeProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochChangeProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochChangeProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GenesisBlockDigest) > 0 {
		i -= len(m.GenesisBlockDigest)
		copy(dAtA[i:], m.GenesisBlockDigest)
		i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.GenesisBlockDigest)))
		i--
		dAtA[i] = 0x22
	}
	if m.Author != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.Author))
		i--
		dAtA[i] = 0x18
	}
	if m.More != 0 {
		i = encodeVarintCheckpoint(dAtA, i, uint64(m.More))
		i--
		dAtA[i] = 0x10
	}
	if len(m.EpochChanges) > 0 {
		for iNdEx := len(m.EpochChanges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EpochChanges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCheckpoint(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *EpochChange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochChange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochChange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Validators) > 0 {
		for iNdEx := len(m.Validators) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Validators[iNdEx])
			copy(dAtA[i:], m.Validators[iNdEx])
			i = encodeVarintCheckpoint(dAtA, i, uint64(len(m.Validators[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Checkpoint != nil {
		{
			size, err := m.Checkpoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCheckpoint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCheckpoint(dAtA []byte, offset int, v uint64) int {
	offset -= sovCheckpoint(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Checkpoint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovCheckpoint(uint64(m.Epoch))
	}
	if m.ExecuteState != nil {
		l = m.ExecuteState.Size()
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.NeedUpdateEpoch {
		n += 2
	}
	if m.NewView != 0 {
		n += 1 + sovCheckpoint(uint64(m.NewView))
	}
	return n
}

func (m *Checkpoint_ExecuteState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovCheckpoint(uint64(m.Height))
	}
	l = len(m.Digest)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	return n
}

func (m *SignedCheckpoint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Checkpoint != nil {
		l = m.Checkpoint.Size()
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if m.Author != 0 {
		n += 1 + sovCheckpoint(uint64(m.Author))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	return n
}

func (m *QuorumCheckpoint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Checkpoint != nil {
		l = m.Checkpoint.Size()
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if len(m.Signatures) > 0 {
		for k, v := range m.Signatures {
			_ = k
			_ = v
			l = 0
			if len(v) > 0 {
				l = 1 + len(v) + sovCheckpoint(uint64(len(v)))
			}
			mapEntrySize := 1 + sovCheckpoint(uint64(k)) + l
			n += mapEntrySize + 1 + sovCheckpoint(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *EpochChangeProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.EpochChanges) > 0 {
		for _, e := range m.EpochChanges {
			l = e.Size()
			n += 1 + l + sovCheckpoint(uint64(l))
		}
	}
	if m.More != 0 {
		n += 1 + sovCheckpoint(uint64(m.More))
	}
	if m.Author != 0 {
		n += 1 + sovCheckpoint(uint64(m.Author))
	}
	l = len(m.GenesisBlockDigest)
	if l > 0 {
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	return n
}

func (m *EpochChange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Checkpoint != nil {
		l = m.Checkpoint.Size()
		n += 1 + l + sovCheckpoint(uint64(l))
	}
	if len(m.Validators) > 0 {
		for _, s := range m.Validators {
			l = len(s)
			n += 1 + l + sovCheckpoint(uint64(l))
		}
	}
	return n
}

func sovCheckpoint(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCheckpoint(x uint64) (n int) {
	return sovCheckpoint(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Checkpoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Checkpoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Checkpoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecuteState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExecuteState == nil {
				m.ExecuteState = &Checkpoint_ExecuteState{}
			}
			if err := m.ExecuteState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NeedUpdateEpoch", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NeedUpdateEpoch = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewView", wireType)
			}
			m.NewView = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewView |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Checkpoint_ExecuteState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecuteState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecuteState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Digest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Digest = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SignedCheckpoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SignedCheckpoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SignedCheckpoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checkpoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Checkpoint == nil {
				m.Checkpoint = &Checkpoint{}
			}
			if err := m.Checkpoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Author", wireType)
			}
			m.Author = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Author |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuorumCheckpoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuorumCheckpoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuorumCheckpoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checkpoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Checkpoint == nil {
				m.Checkpoint = &Checkpoint{}
			}
			if err := m.Checkpoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signatures", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Signatures == nil {
				m.Signatures = make(map[uint64][]byte)
			}
			var mapkey uint64
			mapvalue := []byte{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCheckpoint
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCheckpoint
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapbyteLen uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCheckpoint
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapbyteLen |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intMapbyteLen := int(mapbyteLen)
					if intMapbyteLen < 0 {
						return ErrInvalidLengthCheckpoint
					}
					postbytesIndex := iNdEx + intMapbyteLen
					if postbytesIndex < 0 {
						return ErrInvalidLengthCheckpoint
					}
					if postbytesIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = make([]byte, mapbyteLen)
					copy(mapvalue, dAtA[iNdEx:postbytesIndex])
					iNdEx = postbytesIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipCheckpoint(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthCheckpoint
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Signatures[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochChangeProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochChangeProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochChangeProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochChanges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochChanges = append(m.EpochChanges, &EpochChange{})
			if err := m.EpochChanges[len(m.EpochChanges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field More", wireType)
			}
			m.More = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.More |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Author", wireType)
			}
			m.Author = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Author |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisBlockDigest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GenesisBlockDigest = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochChange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochChange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochChange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checkpoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Checkpoint == nil {
				m.Checkpoint = &QuorumCheckpoint{}
			}
			if err := m.Checkpoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validators", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCheckpoint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validators = append(m.Validators, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCheckpoint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCheckpoint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCheckpoint(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCheckpoint
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCheckpoint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCheckpoint
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCheckpoint
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCheckpoint
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCheckpoint        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCheckpoint          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCheckpoint = fmt.Errorf("proto: unexpected end of group")
)
